# In-Class Programming Activity, Day 8

Delia Walker-Jones

## Task 1A
```{r}
x = runif(100, 20, 70)
y = 5 + 3*x + 2*rnorm(100)
My_data = data.frame(x, y)
```

## Task 1B
```{r}
plot(My_data)
```

## Task 1C
```{r}
LL_line <- function(params){
  m = params[1]
  b = params[2]
  sigma = params[3]
  sum(log(dnorm(y - (m*x + b), sd = sigma)))
}
```

## Task 1D
```{r}
testA = LL_line(c(3, 5, 2))
testB = LL_line(c(4, 1, 10))
```

## Task 1E
```{r}
starting_params <- c(4, 1, 10)
best <- optim(starting_params, LL_line, control = list(fnscale = -1))
```

## Task 2A
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))
```

## Task 2B
```{r}
taxi_likelihood <- function(v, data){
  base_fare = v[1]
  per_mile = v[2]
  rate = 1/v[3]
  waiting_fare <- with(data, fare_amount - (base_fare + per_mile*trip_distance))
  sum(log(dexp(waiting_fare, rate) + 1e-5))
}
```

## Task 2C
```{r}
test <- c(2.00, 4.00, 1/3)

best2 <- optim(test, taxi_likelihood, control = list(fnscale=-1), data = Taxi_trips)
```

## Task 2D
```{r}
plot(fare_amount ~ trip_distance, data = Taxi_trips, col = "forest green" )
abline(best2$par[1], best2$par[2], col = "red")
```











## Test statements

```{r}
scoreActivity::score253(8)
```