# In-Class Programming Activity, Day 10

Delia Walker-Jones

```{r}
library("ISLR")
```


## Logistic Function
```{r}
logistic <- function(x){
  (exp(x))/(1 + (exp(x)))
}

logistic(2)
```

## Linear Combinations
```{r}
linear_combine <- function(data, coefs){
  result <- 0
for (nm in names(coefs)) {
  if (nm == "intercept") {
    result <- result + coefs[[nm]]
  } else {
    if (!(nm %in% names(data))) stop()
    result <- result + coefs[[nm]] * data[[nm]]
  }
  
}
  return(result)
  }
```

## Probabilities
```{r}
LL_logistic <- function(data, coefs, outcome){
  linear_result <- linear_combine(data, coefs)
  prob <- logistic(linear_result)
  likelihood <- ifelse(outcome, prob, 1-prob)

  sum(log(likelihood))
}

LL_logistic(data=Default, 
            coefs = c(intercept = 1, income = -0.0001), 
            outcome = Default$default == "Yes")
```

## Optimize
```{r}
best_coefs <- optim(par = c(intercept = 1, income = -0.0001), fn = LL_logistic, data = Default, outcome = Default$default == "Yes")

best_coefs

glm(default == "Yes" ~ income, data=Default, family="binomial")
```






## Test statements

```{r}
scoreActivity::score253(10)
```