# In-Class Programming Activity, Day 12

Delia Walker-Jones
```{r}
n_cases <- 100
red_mean <- c(1,0)
green_mean <- c(0, -1)
blue_mean <- c(-1, 1)

covar_red <- matrix(c(3, -1.7, -1.7, 1), nrow = 2)
covar_blue <- matrix(c(2, 1.5, 1.5, 3), nrow = 2)

set.seed(1)
One <- cbind(cbind(rnorm(n_cases)), cbind(rnorm(n_cases)))
Two <- cbind(cbind(rnorm(n_cases)), cbind(rnorm(n_cases)))
Three <- cbind(cbind(rnorm(n_cases)), cbind(rnorm(n_cases)))

Red <- One %*% chol(covar_red)
Green <- Two %*% chol(covar_red)
Blue <- Three %*% chol(covar_blue)


#b[,3:5] <- t(t(b[,3:5])-x)
Red <- t(t(Red) + red_mean)
Green <- t(t(Green) + green_mean)
Blue <- t(t(Blue) + blue_mean)

RedData <- data.frame("x" = Red[1,], "y" = Red[,2], "class" = "red", stringsAsFactors = FALSE)
GreenData <- data.frame("x" = Green[1,], "y" = Green[,2], "class" = "green", stringsAsFactors = FALSE)
BlueData <- data.frame("x" = Blue[1,], "y" = Blue[,2], "class" = "blue", stringsAsFactors = FALSE)

Same_sigma <- rbind(RedData, GreenData)
Different_sigma <- rbind(RedData, BlueData)

library(MASS)
# Using Same_sigma
mod_LDA_one <- lda(class ~ x + y, data = Same_sigma)

test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)

mod_QDA_one <- qda(class ~ x + y, data = Same_sigma)

test_QDA_one <- predict(mod_QDA_one, newdata = Same_sigma)

# Using Different_sigma
mod_LDA_two <- lda(class ~ x + y, data = Different_sigma)

test_LDA_two <- predict(mod_LDA_one, newdata = Different_sigma)

mod_QDA_two <- qda(class ~ x + y, data = Different_sigma)

test_QDA_two <- predict(mod_QDA_one, newdata = Different_sigma)

```




## Test statements

```{r}
scoreActivity::score253(12)
```