# In-Class Programming Activity, Day 13

Delia Walker-Jones

```{r}
library(ISLR)
library(mosaic)
```

```{r}
k_fold1 <- function(formula, method = lm, data = mtcars, predfun = predict, k = 10) {
  sets <- (1:length(mtcars) %% k) + 1
  mspe <- numeric(k)
  for (i in 1:k) {
    For_Testing <- mtcars[i == sets, ]
    For_Training <- mtcars[i != sets, ]
    mod <- lm(mpg ~ hp + wt + am, data = For_Training)
    pred_vals <- predict(mod, newdata = For_Testing)
    mspe[i] <- mean((For_Testing[["mpg"]] - pred_vals)^2)
  }
  mean(mspe)
}

k_fold1()
```

```{r}
k_fold <- function(formula, method, data = mtcars, predfun, k = 10) {
  sets <- (1:length(data) %% k) + 1
  mspe <- numeric(k)
  for (i in 1:k) {
    For_Testing <- data[i == sets, ]
    For_Training <- data[i != sets, ]
    mod <- method(formula, data = For_Training)
    pred_vals <- predfun(mod, newdata = For_Testing)
    mspe[i] <- mean((For_Testing[[as.character(formula[[2]])]] - pred_vals)^2)
  }
  mean(mspe)
}

k_fold(formula = mpg ~ hp + wt + am, method = lm, data=mtcars, predfun = predict)
```




## Test statements

```{r}
scoreActivity::score253(13)
```